Repository usnistgov/fipy, pull requests merged in 2018-06, with the labels that each got.

#576 Issue575 skip intermittent levelset failure
  examples/levelSet/electroChem/adsorbingSurfactantEquation.py
Labels: tests

#577 Add support for binder
  INSTALLATION.rst
  README.rst
  binder/environment.yml
  binder/runtime.txt
  examples/index.ipynb
Labels: installation

#580 Revise Navier-Stokes expression in the viscous limit
  examples/flow/stokesCavity.py
Labels: documentation
