Repository usnistgov/fipy, pull requests merged in 2021-11, with the labels that each got.

#822 Set up CI with Azure Pipelines
  .appveyor.yml
  .azure/pipelines.yml
  .azure/templates/install.yml
  .azure/templates/install_bash.yml
  .circleci/config.yml
  .travis.yml
  README.rst
  setup.cfg
Labels: task, CI

#790 fix: stop divide by zero warning in LU solvers
  fipy/solvers/petsc/linearLUSolver.py
  fipy/solvers/pysparse/linearLUSolver.py
  fipy/solvers/scipy/linearLUSolver.py
Labels: bug, solvers

#829 Change `colorbar` argument to valid value
  examples/flow/stokesCavity.py
  examples/flow/stokesNonNewtonian.ipynb
Labels: bug, viewers
