Repository usnistgov/fipy, pull requests merged in 2021-04, with the labels that each got.

#793 Document parallel gmsh
  .appveyor.yml
  .circleci/config.yml
  .travis.yml
  INSTALLATION.rst
  fipy/meshes/gmshMesh.py
Labels: documentation, meshes, parallel

#785 Remove future from setup.py and _setup commands
  .circleci/config.yml
  _setup/_nativize.py
  _setup/build_docs.py
  _setup/changelog.py
  _setup/copy_script.py
  _setup/release.py
  _setup/upload_products.py
  documentation/USAGE.rst
Labels: bug, installation

#794 Fix broken circleSquare with newer Gmsh
  .appveyor.yml
  fipy/meshes/gmshMesh.py
Labels: bug, meshes

#797 Move trilinos tests to Py3k
  .circleci/config.yml
  .travis.yml
Labels: CI, bug, solvers

#798 Replace deprecated numpy types
  .appveyor.yml
  fipy/tests/test.py
  fipy/variables/variable.py
Labels: CI, bug, numerix

#795 Fix Python 2.7 conda environment
  .circleci/config.yml
Labels: CI, bug

#804 Speed up conda environment creation
  .circleci/config.yml
  .travis.yml
  INSTALLATION.rst
Labels: CI, installation
